"""CLI and MCP share the durable runtime while core Dao stays dependency-free."""

import asyncio
import builtins
import json
import os
from pathlib import Path
import re
import subprocess
import sys

import pytest

from dao.agent import Agent
from dao.providers import Reply
from dao.runtime import chat_with_runtime
from dao.store import ConflictError, Store
from dao.workflow import WorkflowJournal


def test_direct_runtime_does_not_import_optional_langgraph(tmp_path, monkeypatch):
    original_import = builtins.__import__

    def without_langgraph(name, *args, **kwargs):
        if name.startswith("langgraph"):
            raise ModuleNotFoundError("LangGraph intentionally unavailable")
        return original_import(name, *args, **kwargs)

    monkeypatch.setattr(builtins, "__import__", without_langgraph)
    with Store(tmp_path / "direct.sqlite3") as store:
        agent = Agent(store)
        result = chat_with_runtime(agent, "/state")
        assert result["text"] == "{}"
        before = store.head(), store.events()
        with pytest.raises(RuntimeError, match=r"dao-agent\[langgraph\]"):
            chat_with_runtime(agent, "/help", runtime="langgraph")
        assert (store.head(), store.events()) == before


def test_runtime_selection_and_direct_run_id_validation(tmp_path):
    with Store(tmp_path / "direct.sqlite3") as store:
        agent = Agent(store)
        before = store.head(), store.events()
        with pytest.raises(ValueError, match="runtime"):
            chat_with_runtime(agent, "hello", runtime="unknown")
        with pytest.raises(ValueError, match="run_id"):
            chat_with_runtime(agent, "hello", run_id="unsupported")
        assert (store.head(), store.events()) == before


def test_runtime_stable_run_id_replays_when_expected_head_is_omitted(tmp_path):
    pytest.importorskip("langgraph.checkpoint.sqlite")

    class Provider:
        reservation_usd = ".1"
        calls = 0

        def respond(self, messages, tools):
            self.calls += 1
            return Reply("hello", 10, 3, ".02", "test")

    provider = Provider()
    path = tmp_path / "runtime.sqlite3"
    checkpoints = tmp_path / "checkpoints.sqlite3"
    with Store(path) as store:
        agent = Agent(store, provider)
        first = chat_with_runtime(agent, "hello", runtime="langgraph",
                                  checkpoint_db=checkpoints, run_id="stable-turn")
        before = store.head(), store.events(), agent.ledger.summary()
        second = chat_with_runtime(agent, "hello", runtime="langgraph",
                                   checkpoint_db=checkpoints, run_id="stable-turn")
        assert second == first
        assert provider.calls == 1
        assert (store.head(), store.events(), agent.ledger.summary()) == before
        with pytest.raises(ConflictError):
            chat_with_runtime(agent, "changed", runtime="langgraph",
                              checkpoint_db=checkpoints, run_id="stable-turn")
        assert provider.calls == 1
    with Store(path) as store:
        reopened = Agent(store, provider)
        assert chat_with_runtime(reopened, "hello", runtime="langgraph",
                                 checkpoint_db=checkpoints, run_id="stable-turn") == first
        assert reopened.ledger.summary()["usage_count"] == 1


def test_graph_runtime_rejects_checkpoint_and_state_database_collision(tmp_path):
    pytest.importorskip("langgraph.checkpoint.sqlite")
    path = tmp_path / "runtime.sqlite3"
    with Store(path) as store:
        agent = Agent(store)
        before = store.head(), store.events()
        with pytest.raises(ValueError, match="differ"):
            chat_with_runtime(agent, "/state", runtime="langgraph", checkpoint_db=path)
        assert (store.head(), store.events()) == before


def test_failed_autogenerated_turn_exposes_recovery_receipt_without_provider_secrets(tmp_path):
    pytest.importorskip("langgraph.checkpoint.sqlite")

    class FailingProvider:
        reservation_usd = ".1"
        calls = 0

        def respond(self, messages, tools):
            self.calls += 1
            raise TimeoutError("private provider request and authorization details")

    with Store(tmp_path / "failure.sqlite3") as store:
        provider = FailingProvider()
        agent = Agent(store, provider)
        with pytest.raises(RuntimeError) as stopped:
            chat_with_runtime(agent, "hello", runtime="langgraph")
        match = re.search(r"dao:chat:([0-9a-f]{32}):reply", str(stopped.value))
        assert match is not None
        run_id, operation_id = match.group(1), match.group(0)
        assert "workflow run " + run_id in str(stopped.value)
        receipt = WorkflowJournal(store).get(operation_id)
        assert receipt["status"] == "failed"
        assert receipt["request"]["run_id"] == run_id
        assert any(event["kind"] == "workflow.failed"
                   and event["payload"]["operation_id"] == operation_id
                   for event in store.events())
        assert agent.ledger.summary()["unknown_count"] == 1
        assert agent.ledger.summary()["reserved_usd"] == "0.100000"
        assert "private provider request" not in str(stopped.value)
        assert "private provider request" not in json.dumps(store.events())
        with pytest.raises(ConflictError):
            chat_with_runtime(agent, "hello", runtime="langgraph", run_id=run_id)
        assert provider.calls == 1


def test_checkpoint_failure_after_completed_chat_reports_receipt_and_replays(tmp_path, monkeypatch):
    sqlite = pytest.importorskip("langgraph.checkpoint.sqlite")

    class Provider:
        reservation_usd = ".1"
        calls = 0

        def respond(self, messages, tools):
            self.calls += 1
            return Reply("completed", 2, 1, ".01", "test")

    with Store(tmp_path / "checkpoint-failure.sqlite3") as store:
        provider = Provider()
        agent = Agent(store, provider)
        operation_id = "dao:chat:checkpoint-failure:reply"
        original_put = sqlite.SqliteSaver.put

        def fail_after_chat(saver, *args, **kwargs):
            with store.lock:
                completed = store.db.execute(
                    "SELECT 1 FROM workflow_results WHERE operation_id=?", (operation_id,),
                ).fetchone()
            if completed:
                raise OSError("private checkpoint backend details")
            return original_put(saver, *args, **kwargs)

        with monkeypatch.context() as patched:
            patched.setattr(sqlite.SqliteSaver, "put", fail_after_chat)
            with pytest.raises(RuntimeError) as stopped:
                chat_with_runtime(agent, "hello", runtime="langgraph", run_id="checkpoint-failure")
        assert operation_id in str(stopped.value)
        assert "private checkpoint backend details" not in str(stopped.value)
        receipt = WorkflowJournal(store).get(operation_id)
        assert receipt["status"] == "completed"
        before = store.events(), agent.ledger.summary(), store.snapshot()
        recovered = chat_with_runtime(agent, "hello", runtime="langgraph",
                                      run_id="checkpoint-failure")
        assert recovered["text"] == "completed"
        assert (store.events(), agent.ledger.summary(), store.snapshot()) == before
        assert provider.calls == 1


def test_cli_langgraph_roundtrip_replays_between_processes(tmp_path):
    pytest.importorskip("langgraph.checkpoint.sqlite")
    dao_path = tmp_path / "cli.sqlite3"
    checkpoint_path = tmp_path / "checkpoints.sqlite3"
    args = [sys.executable, "-m", "dao.cli", "--db", str(dao_path), "chat", "/state",
            "--runtime", "langgraph", "--checkpoint-db", str(checkpoint_path),
            "--run-id", "cli-stable", "--json"]

    def call(command):
        return subprocess.run(command, cwd=Path(__file__).resolve().parents[1],
                              capture_output=True, text=True, timeout=30)

    first_process = call(args)
    assert first_process.returncode == 0, first_process.stderr
    first = json.loads(first_process.stdout)
    assert first["workflow"]["run_id"] == "cli-stable"
    second_process = call(args)
    assert second_process.returncode == 0, second_process.stderr
    assert json.loads(second_process.stdout) == first
    with Store(dao_path) as store:
        assert len(store.snapshot()["messages"]) == 2
    changed = list(args)
    changed[changed.index("/state")] = "/help"
    conflict = call(changed)
    assert conflict.returncode == 1
    assert "different inputs" in conflict.stderr


def test_mcp_langgraph_roundtrip_keeps_adjudication_trusted_and_replays(tmp_path):
    pytest.importorskip("langgraph.checkpoint.sqlite")
    pytest.importorskip("mcp")
    from mcp import ClientSession, StdioServerParameters
    from mcp.client.stdio import stdio_client

    def tool_payload(result):
        if result.structuredContent is not None:
            return result.structuredContent
        return json.loads(result.content[0].text)

    async def run():
        parameters = StdioServerParameters(
            command=sys.executable,
            args=["-m", "dao.mcp_server", "--db", str(tmp_path / "mcp.sqlite3"),
                  "--runtime", "langgraph", "--checkpoint-db", str(tmp_path / "checkpoints.db")],
            env=dict(os.environ),
        )
        async with stdio_client(parameters) as (read, write):
            async with ClientSession(read, write) as session:
                await session.initialize()
                tools = await session.list_tools()
                names = {tool.name for tool in tools.tools}
                assert "workflow_operation" in names
                assert "adjudicate_action" not in names
                request = {"message": "/remember preference \"tea\"", "run_id": "mcp-stable"}
                first = await session.call_tool("chat", request)
                assert not first.isError
                result = tool_payload(first)
                assert result["proposal_ids"]
                assert result["workflow"]["run_id"] == "mcp-stable"
                second = await session.call_tool("chat", request)
                assert not second.isError
                assert tool_payload(second) == result
                read_state = await session.call_tool("read_state", {})
                assert tool_payload(read_state)["state"]["memory"] == {}
                operation = await session.call_tool("workflow_operation", {
                    "operation_id": result["workflow"]["operation_id"],
                })
                assert tool_payload(operation)["status"] == "completed"
                refused = await session.call_tool("execute_action", {
                    "proposal_id": result["proposal_ids"][0], "expected_head": result["head"],
                })
                assert refused.isError

    asyncio.run(run())
